import {
  SurfSchool,
  User,
  Instructor,
  ScheduleSlot,
  ClassSession,
  Booking,
  StudentEvaluation,
  InstructorReview,
  MembershipPlan,
  FinancialRecord,
  AppNotification,
  WaveConditions,
} from '../types';

export const INITIAL_SCHOOLS: SurfSchool[] = [
  {
    id: 'school_1',
    name: 'Maresia Surf Academy',
    slug: 'maresia-surf-academy',
    logo: '🌊',
    coverImage: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200&q=80',
    beachSpot: 'Praia de Maresias - Canto do Moreira',
    city: 'São Sebastião',
    state: 'SP',
    phone: '(12) 99876-5432',
    email: 'contato@maresiassurfacademy.com.br',
    ownerId: 'user_owner_1',
    ownerName: 'Carlos "Kadu" Silveira',
    ownerEmail: 'kadu@maresiassurf.com',
    description: 'Escola de surf de alta performance e formação de novos surfistas. Mais de 15 anos ensinando a arte de deslizar nas ondas com total segurança.',
    active: true,
    maxStudentsPerClass: 5,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'school_2',
    name: 'Floripa Joaquina Surf Club',
    slug: 'floripa-joaquina-surf-club',
    logo: '🏄‍♂️',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    beachSpot: 'Praia da Joaquina',
    city: 'Florianópolis',
    state: 'SC',
    phone: '(48) 98765-4321',
    email: 'aloha@joaquinasurf.com.br',
    ownerId: 'user_owner_2',
    ownerName: 'Teco Marins',
    ownerEmail: 'teco@joaquinasurf.com.br',
    description: 'Tradição e paixão pelo surf nas dunas e ondas clássicas da Joaquina.',
    active: true,
    maxStudentsPerClass: 4,
    createdAt: '2024-03-10T14:00:00Z',
  },
];

export const INITIAL_USERS: User[] = [
  // Super Admin
  {
    id: 'user_super_admin',
    name: 'Administrador Master',
    email: 'admin@surfflow.com',
    password: 'admin',
    role: 'super_admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    phone: '(11) 99999-0001',
    status: 'active',
    joinedDate: '2024-01-01',
  },
  // Dono da Escola 1
  {
    id: 'user_owner_1',
    name: 'Carlos "Kadu" Silveira',
    email: 'kadu@maresiassurf.com',
    password: '123',
    role: 'school_owner',
    schoolId: 'school_1',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    phone: '(12) 99876-5432',
    status: 'active',
    joinedDate: '2024-01-15',
  },
  // Dono da Escola 2
  {
    id: 'user_owner_2',
    name: 'Teco Marins',
    email: 'teco@joaquinasurf.com.br',
    password: '123',
    role: 'school_owner',
    schoolId: 'school_2',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    phone: '(48) 98765-4321',
    status: 'active',
    joinedDate: '2024-03-10',
  },
  // Instrutores
  {
    id: 'user_instructor_1',
    name: 'Gabriel "Biel" Toledo',
    email: 'biel@maresiassurf.com',
    password: '123',
    role: 'instructor',
    schoolId: 'school_1',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
    phone: '(12) 99123-4567',
    status: 'active',
    joinedDate: '2024-02-01',
  },
  {
    id: 'user_instructor_2',
    name: 'Maya Albuquerque',
    email: 'maya@maresiassurf.com',
    password: '123',
    role: 'instructor',
    schoolId: 'school_1',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    phone: '(12) 99234-5678',
    status: 'active',
    joinedDate: '2024-02-15',
  },
  {
    id: 'user_instructor_3',
    name: 'Matheus "Tubarão" Ramos',
    email: 'matheus@maresiassurf.com',
    password: '123',
    role: 'instructor',
    schoolId: 'school_1',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    phone: '(12) 99345-6789',
    status: 'active',
    joinedDate: '2024-03-01',
  },
  // Alunos
  {
    id: 'user_student_1',
    name: 'Lucas Ferreira',
    email: 'lucas@gmail.com',
    password: '123',
    role: 'student',
    schoolId: 'school_1',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    phone: '(11) 98877-6655',
    status: 'active',
    planId: 'plan_2',
    skillLevel: 'intermediario',
    boardType: 'Funboard 7\'2',
    emergencyContact: 'Mariana (Esposa) - (11) 98877-0000',
    joinedDate: '2024-05-10',
  },
  {
    id: 'user_student_2',
    name: 'Sofia Marés',
    email: 'sofia@gmail.com',
    password: '123',
    role: 'student',
    schoolId: 'school_1',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    phone: '(11) 97766-5544',
    status: 'active',
    planId: 'plan_1',
    skillLevel: 'iniciante',
    boardType: 'Softboard 8\'0',
    emergencyContact: 'Roberto (Pai) - (11) 97766-0000',
    joinedDate: '2024-06-01',
  },
  {
    id: 'user_student_3',
    name: 'Bruno Ondas',
    email: 'bruno@gmail.com',
    password: '123',
    role: 'student',
    schoolId: 'school_1',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    phone: '(11) 96655-4433',
    status: 'inactive', // Aluno inativo / mensalidade pendente
    planId: 'plan_1',
    skillLevel: 'iniciante',
    boardType: 'Softboard 7\'6',
    emergencyContact: 'Paula (Irmã) - (11) 96655-0000',
    joinedDate: '2024-04-12',
  },
  {
    id: 'user_student_4',
    name: 'Camila Zanetti',
    email: 'camila@gmail.com',
    password: '123',
    role: 'student',
    schoolId: 'school_1',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    phone: '(11) 95544-3322',
    status: 'active',
    planId: 'plan_3',
    skillLevel: 'avancado',
    boardType: 'Shortboard 6\'0 Fish',
    emergencyContact: 'André (Noivo) - (11) 95544-0000',
    joinedDate: '2024-02-20',
  },
];

export const INITIAL_INSTRUCTORS: Instructor[] = [
  {
    id: 'inst_1',
    userId: 'user_instructor_1',
    schoolId: 'school_1',
    name: 'Gabriel "Biel" Toledo',
    email: 'biel@maresiassurf.com',
    phone: '(12) 99123-4567',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
    bio: 'Ex-competidor do circuito paulista com 12 anos de experiência. Focado em paciência, didática de remada e leitura apurada das séries.',
    crefOrCert: 'CREF 089234-G/SP | ISA Nível 2',
    specialties: ['Iniciantes', 'Postura & Drop', 'Leitura de Séries'],
    rating: 4.9,
    reviewCount: 38,
    colorTag: 'emerald',
    active: true,
    yearsExperience: 12,
  },
  {
    id: 'inst_2',
    userId: 'user_instructor_2',
    schoolId: 'school_1',
    name: 'Maya Albuquerque',
    email: 'maya@maresiassurf.com',
    phone: '(12) 99234-5678',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    bio: 'Surfista de ondas pesadas e especialista em biomecânica do surf. Transmite confiança total para perder o medo do mar e dropar com estabilidade.',
    crefOrCert: 'CREF 074112-G/SP | Salva-Vidas CBMSC',
    specialties: ['Confiança no Mar', 'Evolução Intermediária', 'Mulheres no Surf'],
    rating: 5.0,
    reviewCount: 42,
    colorTag: 'cyan',
    active: true,
    yearsExperience: 9,
  },
  {
    id: 'inst_3',
    userId: 'user_instructor_3',
    schoolId: 'school_1',
    name: 'Matheus "Tubarão" Ramos',
    email: 'matheus@maresiassurf.com',
    phone: '(12) 99345-6789',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    bio: 'Especialista em preparação funcional e técnicas avançadas de manobras de linha, batida e rasgada.',
    crefOrCert: 'CREF 065431-G/SP | Pós em Fisiologia do Exercício',
    specialties: ['Surf Avançado', 'Transição para Pranchinha', 'Manobras de Borda'],
    rating: 4.8,
    reviewCount: 29,
    colorTag: 'amber',
    active: true,
    yearsExperience: 14,
  },
];

export const INITIAL_PLANS: MembershipPlan[] = [
  {
    id: 'plan_1',
    schoolId: 'school_1',
    name: 'Plano Marola (2x / Semana)',
    description: 'Ideal para quem está começando e quer consistência semanal nas ondas.',
    price: 320,
    classesPerWeek: 2,
    billingPeriod: 'mensal',
  },
  {
    id: 'plan_2',
    schoolId: 'school_1',
    name: 'Plano Swell (3x / Semana)',
    description: 'Nosso plano mais popular. Evolução acelerada com acompanhamento próximo.',
    price: 450,
    classesPerWeek: 3,
    billingPeriod: 'mensal',
  },
  {
    id: 'plan_3',
    schoolId: 'school_1',
    name: 'Plano Pro Aloha (Ilimitado)',
    description: 'Aulas ilimitadas durante todo o mês + empréstimo de pranchas e lycra.',
    price: 680,
    classesPerWeek: 'ilimitado',
    billingPeriod: 'mensal',
  },
  {
    id: 'plan_4',
    schoolId: 'school_1',
    name: 'Aula Avulsa Experimental',
    description: '1 aula de 1h30 com prancha inclusa e instrutor individual/dupla.',
    price: 150,
    classesPerWeek: 1,
    billingPeriod: 'avulso',
  },
];

export const INITIAL_SCHEDULE_SLOTS: ScheduleSlot[] = [
  // Gabriel
  { id: 'slot_1', schoolId: 'school_1', instructorId: 'inst_1', dayOfWeek: 1, startTime: '06:30', endTime: '08:00', maxStudents: 5, level: 'iniciante', spot: 'Canto do Moreira', active: true },
  { id: 'slot_2', schoolId: 'school_1', instructorId: 'inst_1', dayOfWeek: 1, startTime: '08:30', endTime: '10:00', maxStudents: 5, level: 'todos', spot: 'Canto do Moreira', active: true },
  { id: 'slot_3', schoolId: 'school_1', instructorId: 'inst_1', dayOfWeek: 1, startTime: '16:00', endTime: '17:30', maxStudents: 5, level: 'todos', spot: 'Canto do Moreira', active: true },
  
  { id: 'slot_4', schoolId: 'school_1', instructorId: 'inst_1', dayOfWeek: 3, startTime: '06:30', endTime: '08:00', maxStudents: 5, level: 'iniciante', spot: 'Canto do Moreira', active: true },
  { id: 'slot_5', schoolId: 'school_1', instructorId: 'inst_1', dayOfWeek: 3, startTime: '08:30', endTime: '10:00', maxStudents: 5, level: 'intermediario', spot: 'Canto do Moreira', active: true },
  
  { id: 'slot_6', schoolId: 'school_1', instructorId: 'inst_1', dayOfWeek: 5, startTime: '07:00', endTime: '08:30', maxStudents: 5, level: 'todos', spot: 'Canto do Moreira', active: true },
  { id: 'slot_7', schoolId: 'school_1', instructorId: 'inst_1', dayOfWeek: 6, startTime: '08:00', endTime: '09:30', maxStudents: 6, level: 'iniciante', spot: 'Canto do Moreira', active: true },
  { id: 'slot_8', schoolId: 'school_1', instructorId: 'inst_1', dayOfWeek: 0, startTime: '08:00', endTime: '09:30', maxStudents: 6, level: 'todos', spot: 'Canto do Moreira', active: true },

  // Maya
  { id: 'slot_9', schoolId: 'school_1', instructorId: 'inst_2', dayOfWeek: 2, startTime: '07:00', endTime: '08:30', maxStudents: 4, level: 'iniciante', spot: 'Maresias Meio', active: true },
  { id: 'slot_10', schoolId: 'school_1', instructorId: 'inst_2', dayOfWeek: 2, startTime: '09:00', endTime: '10:30', maxStudents: 4, level: 'intermediario', spot: 'Maresias Meio', active: true },
  { id: 'slot_11', schoolId: 'school_1', instructorId: 'inst_2', dayOfWeek: 4, startTime: '07:00', endTime: '08:30', maxStudents: 4, level: 'todos', spot: 'Maresias Meio', active: true },
  { id: 'slot_12', schoolId: 'school_1', instructorId: 'inst_2', dayOfWeek: 4, startTime: '16:00', endTime: '17:30', maxStudents: 4, level: 'iniciante', spot: 'Maresias Meio', active: true },
  { id: 'slot_13', schoolId: 'school_1', instructorId: 'inst_2', dayOfWeek: 6, startTime: '09:30', endTime: '11:00', maxStudents: 5, level: 'todos', spot: 'Maresias Meio', active: true },

  // Matheus
  { id: 'slot_14', schoolId: 'school_1', instructorId: 'inst_3', dayOfWeek: 1, startTime: '09:00', endTime: '10:30', maxStudents: 4, level: 'intermediario', spot: 'Canto Bravo', active: true },
  { id: 'slot_15', schoolId: 'school_1', instructorId: 'inst_3', dayOfWeek: 3, startTime: '15:30', endTime: '17:00', maxStudents: 4, level: 'avancado', spot: 'Canto Bravo', active: true },
  { id: 'slot_16', schoolId: 'school_1', instructorId: 'inst_3', dayOfWeek: 5, startTime: '09:00', endTime: '10:30', maxStudents: 4, level: 'avancado', spot: 'Canto Bravo', active: true },
  { id: 'slot_17', schoolId: 'school_1', instructorId: 'inst_3', dayOfWeek: 6, startTime: '06:30', endTime: '08:00', maxStudents: 4, level: 'intermediario', spot: 'Canto Bravo', active: true },
];

export const INITIAL_WAVE_FORECAST: WaveConditions = {
  height: '1.2m - 1.5m (Série boa)',
  swell: 'Sul / Sudeste (Período: 11s)',
  wind: 'Terral Fraco (4-6 nós cedo)',
  tide: 'Secando (Baixa-mar às 10:45)',
  waterTemp: '23°C (Água morna e cristalina)',
};

// Generate realistic dynamic dates based on today
const today = new Date();
const formatDate = (offsetDays: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_SESSIONS: ClassSession[] = [
  {
    id: 'session_past_1',
    schoolId: 'school_1',
    instructorId: 'inst_1',
    date: formatDate(-3),
    startTime: '06:30',
    endTime: '08:00',
    spot: 'Canto do Moreira',
    level: 'iniciante',
    maxStudents: 5,
    enrolledStudentIds: ['user_student_1', 'user_student_2'],
    status: 'completed',
    waveConditions: INITIAL_WAVE_FORECAST,
  },
  {
    id: 'session_past_2',
    schoolId: 'school_1',
    instructorId: 'inst_2',
    date: formatDate(-1),
    startTime: '07:00',
    endTime: '08:30',
    spot: 'Maresias Meio',
    level: 'iniciante',
    maxStudents: 4,
    enrolledStudentIds: ['user_student_2', 'user_student_4'],
    status: 'completed',
    waveConditions: INITIAL_WAVE_FORECAST,
  },
  // Sessão Hoje
  {
    id: 'session_today_1',
    schoolId: 'school_1',
    instructorId: 'inst_1',
    date: formatDate(0),
    startTime: '06:30',
    endTime: '08:00',
    spot: 'Canto do Moreira',
    level: 'todos',
    maxStudents: 5,
    enrolledStudentIds: ['user_student_1'],
    status: 'scheduled',
    waveConditions: INITIAL_WAVE_FORECAST,
  },
  {
    id: 'session_today_2',
    schoolId: 'school_1',
    instructorId: 'inst_2',
    date: formatDate(0),
    startTime: '09:00',
    endTime: '10:30',
    spot: 'Maresias Meio',
    level: 'intermediario',
    maxStudents: 4,
    enrolledStudentIds: ['user_student_4'],
    status: 'scheduled',
    waveConditions: INITIAL_WAVE_FORECAST,
  },
  {
    id: 'session_today_3',
    schoolId: 'school_1',
    instructorId: 'inst_1',
    date: formatDate(0),
    startTime: '16:00',
    endTime: '17:30',
    spot: 'Canto do Moreira',
    level: 'todos',
    maxStudents: 5,
    enrolledStudentIds: ['user_student_1', 'user_student_2'],
    status: 'scheduled',
    waveConditions: INITIAL_WAVE_FORECAST,
  },
  // Sessões Próximos Dias
  {
    id: 'session_fut_1',
    schoolId: 'school_1',
    instructorId: 'inst_1',
    date: formatDate(1),
    startTime: '06:30',
    endTime: '08:00',
    spot: 'Canto do Moreira',
    level: 'iniciante',
    maxStudents: 5,
    enrolledStudentIds: ['user_student_2'],
    status: 'scheduled',
    waveConditions: INITIAL_WAVE_FORECAST,
  },
  {
    id: 'session_fut_2',
    schoolId: 'school_1',
    instructorId: 'inst_2',
    date: formatDate(1),
    startTime: '07:00',
    endTime: '08:30',
    spot: 'Maresias Meio',
    level: 'todos',
    maxStudents: 4,
    enrolledStudentIds: [],
    status: 'scheduled',
    waveConditions: INITIAL_WAVE_FORECAST,
  },
  {
    id: 'session_fut_3',
    schoolId: 'school_1',
    instructorId: 'inst_3',
    date: formatDate(2),
    startTime: '09:00',
    endTime: '10:30',
    spot: 'Canto Bravo',
    level: 'avancado',
    maxStudents: 4,
    enrolledStudentIds: ['user_student_4'],
    status: 'scheduled',
    waveConditions: INITIAL_WAVE_FORECAST,
  },
  {
    id: 'session_fut_4',
    schoolId: 'school_1',
    instructorId: 'inst_1',
    date: formatDate(3),
    startTime: '08:00',
    endTime: '09:30',
    spot: 'Canto do Moreira',
    level: 'todos',
    maxStudents: 5,
    enrolledStudentIds: [],
    status: 'scheduled',
    waveConditions: INITIAL_WAVE_FORECAST,
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book_past_1',
    schoolId: 'school_1',
    sessionId: 'session_past_1',
    studentId: 'user_student_1',
    instructorId: 'inst_1',
    date: formatDate(-3),
    startTime: '06:30',
    endTime: '08:00',
    spot: 'Canto do Moreira',
    status: 'completed',
    bookedAt: '2024-10-01T10:00:00Z',
    attendanceStatus: 'present',
  },
  {
    id: 'book_past_2',
    schoolId: 'school_1',
    sessionId: 'session_past_1',
    studentId: 'user_student_2',
    instructorId: 'inst_1',
    date: formatDate(-3),
    startTime: '06:30',
    endTime: '08:00',
    spot: 'Canto do Moreira',
    status: 'completed',
    bookedAt: '2024-10-01T11:20:00Z',
    attendanceStatus: 'present',
  },
  {
    id: 'book_past_3',
    schoolId: 'school_1',
    sessionId: 'session_past_2',
    studentId: 'user_student_2',
    instructorId: 'inst_2',
    date: formatDate(-1),
    startTime: '07:00',
    endTime: '08:30',
    spot: 'Maresias Meio',
    status: 'completed',
    bookedAt: '2024-10-03T15:00:00Z',
    attendanceStatus: 'present',
  },
  // Atuais
  {
    id: 'book_current_1',
    schoolId: 'school_1',
    sessionId: 'session_today_1',
    studentId: 'user_student_1',
    instructorId: 'inst_1',
    date: formatDate(0),
    startTime: '06:30',
    endTime: '08:00',
    spot: 'Canto do Moreira',
    status: 'confirmed',
    bookedAt: '2024-10-05T09:12:00Z',
  },
  {
    id: 'book_current_2',
    schoolId: 'school_1',
    sessionId: 'session_today_3',
    studentId: 'user_student_1',
    instructorId: 'inst_1',
    date: formatDate(0),
    startTime: '16:00',
    endTime: '17:30',
    spot: 'Canto do Moreira',
    status: 'confirmed',
    bookedAt: '2024-10-05T14:30:00Z',
  },
  {
    id: 'book_current_3',
    schoolId: 'school_1',
    sessionId: 'session_today_3',
    studentId: 'user_student_2',
    instructorId: 'inst_1',
    date: formatDate(0),
    startTime: '16:00',
    endTime: '17:30',
    spot: 'Canto do Moreira',
    status: 'confirmed',
    bookedAt: '2024-10-05T14:35:00Z',
  },
  {
    id: 'book_current_4',
    schoolId: 'school_1',
    sessionId: 'session_fut_1',
    studentId: 'user_student_2',
    instructorId: 'inst_1',
    date: formatDate(1),
    startTime: '06:30',
    endTime: '08:00',
    spot: 'Canto do Moreira',
    status: 'confirmed',
    bookedAt: '2024-10-06T08:00:00Z',
  },
];

export const INITIAL_EVALUATIONS: StudentEvaluation[] = [
  {
    id: 'eval_1',
    sessionId: 'session_past_1',
    schoolId: 'school_1',
    instructorId: 'inst_1',
    studentId: 'user_student_1',
    date: formatDate(-3),
    skills: {
      paddling: 4,
      popupDrop: 4,
      balance: 4,
      waveReading: 3,
      seaSafety: 5,
    },
    overallRating: 4,
    wavesCaught: 7,
    boardUsed: 'Funboard 7\'2',
    notes: 'Lucas teve um desempenho excelente hoje! Conseguiu posicionar-se no pico correto e dropou 7 ondas com velocidade. A remada está bem encaixada.',
    coachTips: 'Próxima meta: antecipar 1 segundo antes a subida para pegar a parede ainda abrindo para a direita.',
    createdAt: '2024-10-04T10:00:00Z',
  },
  {
    id: 'eval_2',
    sessionId: 'session_past_1',
    schoolId: 'school_1',
    instructorId: 'inst_1',
    studentId: 'user_student_2',
    date: formatDate(-3),
    skills: {
      paddling: 3,
      popupDrop: 3,
      balance: 4,
      waveReading: 2,
      seaSafety: 4,
    },
    overallRating: 3.5,
    wavesCaught: 4,
    boardUsed: 'Softboard 8\'0',
    notes: 'Sofia venceu o medo do drop nas ondas de 1m na arrebentação! Ficou bem calma nas séries e subiu com o peito alto.',
    coachTips: 'Mantenha os olhos fixos na praia ou no ombro da onda ao ficar de pé, evite olhar para o bico da prancha.',
    createdAt: '2024-10-04T10:15:00Z',
  },
  {
    id: 'eval_3',
    sessionId: 'session_past_2',
    schoolId: 'school_1',
    instructorId: 'inst_2',
    studentId: 'user_student_2',
    date: formatDate(-1),
    skills: {
      paddling: 4,
      popupDrop: 4,
      balance: 4,
      waveReading: 3,
      seaSafety: 5,
    },
    overallRating: 4,
    wavesCaught: 6,
    boardUsed: 'Softboard 8\'0',
    notes: 'Evolução nítida da Sofia! Corrigiu a posição das mãos no drop e andou mais de 25 metros em 3 ondas.',
    coachTips: 'Já está quase pronta para testar uma prancha 7\'6 na próxima semana!',
    createdAt: '2024-10-06T12:00:00Z',
  },
];

export const INITIAL_REVIEWS: InstructorReview[] = [
  {
    id: 'rev_1',
    sessionId: 'session_past_1',
    schoolId: 'school_1',
    instructorId: 'inst_1',
    studentId: 'user_student_1',
    studentName: 'Lucas Ferreira',
    rating: 5,
    didactics: 5,
    safetyAttention: 5,
    vibe: 5,
    comment: 'O professor Biel tem uma paciência fantástica. Me ensinou o ponto exato da quebra no Moreira e me deu muita segurança nas séries maiores.',
    createdAt: '2024-10-04T14:30:00Z',
  },
  {
    id: 'rev_2',
    sessionId: 'session_past_2',
    schoolId: 'school_1',
    instructorId: 'inst_2',
    studentId: 'user_student_2',
    studentName: 'Sofia Marés',
    rating: 5,
    didactics: 5,
    safetyAttention: 5,
    vibe: 5,
    comment: 'A Maya é simplesmente maravilhosa! Me ajudou a superar o medo das ondas da bancada e a sensação de surfar em pé foi indescritível.',
    createdAt: '2024-10-06T13:40:00Z',
  },
];

export const INITIAL_FINANCIAL_RECORDS: FinancialRecord[] = [
  {
    id: 'fin_1',
    schoolId: 'school_1',
    studentId: 'user_student_1',
    studentName: 'Lucas Ferreira',
    planId: 'plan_2',
    planName: 'Plano Swell (3x / Semana)',
    amount: 450,
    dueDate: '2024-10-10',
    paidDate: '2024-10-02',
    status: 'paid',
    paymentMethod: 'pix',
    referenceMonth: 'Outubro/2026',
    notes: 'Comprovante Pix confirmado automaticamente.',
  },
  {
    id: 'fin_2',
    schoolId: 'school_1',
    studentId: 'user_student_2',
    studentName: 'Sofia Marés',
    planId: 'plan_1',
    planName: 'Plano Marola (2x / Semana)',
    amount: 320,
    dueDate: '2024-10-15',
    paidDate: '2024-10-05',
    status: 'paid',
    paymentMethod: 'cartao',
    referenceMonth: 'Outubro/2026',
    notes: 'Recorrência no cartão de crédito.',
  },
  {
    id: 'fin_3',
    schoolId: 'school_1',
    studentId: 'user_student_3',
    studentName: 'Bruno Ondas',
    planId: 'plan_1',
    planName: 'Plano Marola (2x / Semana)',
    amount: 320,
    dueDate: '2024-10-05',
    status: 'overdue', // Atrasado
    referenceMonth: 'Outubro/2026',
    notes: 'Vencido há 2 dias. Agendamento suspenso até regularização.',
  },
  {
    id: 'fin_4',
    schoolId: 'school_1',
    studentId: 'user_student_4',
    studentName: 'Camila Zanetti',
    planId: 'plan_3',
    planName: 'Plano Pro Aloha (Ilimitado)',
    amount: 680,
    dueDate: '2024-10-20',
    status: 'pending', // Pendente dentro do prazo
    referenceMonth: 'Outubro/2026',
    notes: 'Lembrete automático agendado para 3 dias antes do vencimento.',
  },
  {
    id: 'fin_5',
    schoolId: 'school_1',
    studentId: 'user_student_1',
    studentName: 'Lucas Ferreira',
    planId: 'plan_2',
    planName: 'Plano Swell (3x / Semana)',
    amount: 450,
    dueDate: '2024-09-10',
    paidDate: '2024-09-08',
    status: 'paid',
    paymentMethod: 'pix',
    referenceMonth: 'Setembro/2026',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    recipientId: 'user_student_1',
    schoolId: 'school_1',
    title: '🏄‍♂️ Aula Confirmada!',
    message: 'Sua aula de surf com o instrutor Gabriel "Biel" Toledo no Canto do Moreira foi confirmada com sucesso.',
    type: 'booking_confirmed',
    read: false,
    createdAt: '2024-10-05T09:12:00Z',
  },
  {
    id: 'notif_2',
    recipientId: 'user_student_1',
    schoolId: 'school_1',
    title: '⭐ Nova Avaliação Técnica!',
    message: 'O instrutor Biel publicou o relatório da sua última aula: "7 ondas surfadas e remada sólida!". Confira o feedback técnico.',
    type: 'evaluation_posted',
    read: true,
    createdAt: '2024-10-04T10:05:00Z',
  },
  {
    id: 'notif_3',
    recipientId: 'user_owner_1',
    schoolId: 'school_1',
    title: '💰 Mensalidade Recebida',
    message: 'Lucas Ferreira efetuou o pagamento da mensalidade de Outubro/2026 via Pix (R$ 450,00).',
    type: 'payment_received',
    read: false,
    createdAt: '2024-10-02T11:00:00Z',
  },
  {
    id: 'notif_4',
    recipientId: 'user_instructor_1',
    schoolId: 'school_1',
    title: '📅 Nova Inscrição na Turma',
    message: 'O aluno Lucas Ferreira reservou vaga na sua aula de hoje às 06:30 no Canto do Moreira.',
    type: 'booking_confirmed',
    read: false,
    createdAt: '2024-10-05T09:12:00Z',
  },
  {
    id: 'notif_5',
    recipientId: 'user_student_3',
    schoolId: 'school_1',
    title: '⚠️ Aviso de Mensalidade Vencida',
    message: 'Sua mensalidade venceu em 05/10. Regularize para reativar o agendamento de novas aulas de surf.',
    type: 'payment_reminder',
    read: false,
    createdAt: '2024-10-06T08:00:00Z',
  },
];
